version: '3'
services:
  app-service:
    build: ./app
    command: gunicorn -b 0.0.0.0:3011 app:app
    restart: always
    expose:
      - 3011
    
    volumes: 
      - type: bind
        source: ./app
        target: /app
    
    ports: 
      - "3011:3011"

    depends_on:
      - mongo

  
  mongo:
    image: mongo
    ports: 
      - "27017:27017"